In [1]:
import numpy as np

In [2]:
# Exercício 1: Dada uma matriz 2D, normalize cada linha subtraindo a média da linha.
matriz2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

linhas = matriz2D.shape[0]
colunas = matriz2D.shape[1]

matrizNormalizada = np.empty((0,colunas))

for i in range(linhas):
    
    somaLinha = matriz2D[i].sum()
    mediaLinha = somaLinha/colunas
    matriz = matriz2D[i]-mediaLinha
    matrizNormalizada = np.block([[matrizNormalizada],[matriz]])
    
matrizNormalizada



array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [78]:


matriz2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

medias = np.mean(matriz2D, axis=1)  # Médias de cada linha
matrizNormalizada = matriz2D - medias[:, np.newaxis]  # Subtração das médias por linha

print(matrizNormalizada)

[ 2.  5.  8. 11.]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [135]:
# Exercício 2: Dado um array numpy 1D, encontre o valor mais próximo de um número específico.
array = np.arange(start = 1, stop=100 + 1, step =1.5, dtype= float)
numeroExemplo = 1.9
print(array)
if numeroExemplo in array:
    print(numeroExemplo)
else:
    array = np.append(array,numeroExemplo)
    array.sort()
    shape = np.shape(array)
    
    if array[0] == numeroExemplo:
        print(array[1])
    elif  array[shape[0]-1] == numeroExemplo:
        print(array[shape[0]-2] )
        
    else:
        index = np.where(array == numeroExemplo)
        indexmaior = array[index[0]+1]
        indexmenor=array[index[0]-1]
        
        if numeroExemplo - indexmenor > indexmaior - numeroExemplo:
            print(array[index[0]+1])
        else:
            print(array[index[0]-1])

    

[  1.    2.5   4.    5.5   7.    8.5  10.   11.5  13.   14.5  16.   17.5
  19.   20.5  22.   23.5  25.   26.5  28.   29.5  31.   32.5  34.   35.5
  37.   38.5  40.   41.5  43.   44.5  46.   47.5  49.   50.5  52.   53.5
  55.   56.5  58.   59.5  61.   62.5  64.   65.5  67.   68.5  70.   71.5
  73.   74.5  76.   77.5  79.   80.5  82.   83.5  85.   86.5  88.   89.5
  91.   92.5  94.   95.5  97.   98.5 100. ]
[2.5]


In [139]:
# Array numpy 1D
array = np.arange(start = 1, stop=100 + 1, step =1.5, dtype= float)
# Número específico
numero_especifico = 9
# Encontrar o valor mais próximo
valor_proximo = array[np.abs(array - numero_especifico).argmin()]
print(valor_proximo)

8.5


In [48]:
# Exercício 3: Dada uma matriz 2D, substitua todos os valores abaixo de um limiar por zero.
matriz2D = np.random.randint(low = 1, high=101, size = (5,5))
limiar = 20

matrizZeros = np.where(matriz2D <= limiar, 0, matriz2D)

matrizZeros


array([[79, 27, 91, 36,  0],
       [86, 21, 93, 37, 68],
       [67,  0,  0, 67, 28],
       [99, 95, 48, 37, 32],
       [94, 50, 61, 87, 93]])

In [56]:
# Exercício 4: Dado um array numpy 1D, encontre os índices dos elementos que satisfazem uma determinada condição.
array1D = np.arange(start=1, stop=50, step = 3)
display(array1D)

np.where(array1D % 2 == 0)


array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

(array([ 1,  3,  5,  7,  9, 11, 13, 15], dtype=int64),)

In [71]:
# Exercício 5: Dada uma matriz 2D, calcule a média de cada coluna e subtraia essa média de cada elemento da coluna.
matriz2D = np.array([[2,2,4,8],[5,3,5,3],[5,4,6,10]])
linha1 = np.mean(matriz2D, axis=0)
display(linha1)
matriznormalizada = matriz2D - linha1
display(matriz2D)
matriznormalizada

array([4., 3., 5., 7.])

array([[ 2,  2,  4,  8],
       [ 5,  3,  5,  3],
       [ 5,  4,  6, 10]])

array([[-2., -1., -1.,  1.],
       [ 1.,  0.,  0., -4.],
       [ 1.,  1.,  1.,  3.]])

In [145]:
# Exercício 6: Dado um array numpy 1D, encontre os top N valores máximos sem usar o método numpy.sort().
array1D = np.random.randint(low = 1, high= 10, size = 10)
display(array1D)
arrayTop = np.array([])

for i in range(5):
    arrayTop = np.append(arrayTop,array1D.max())
    indice_a_deletar = np.where(array1D == array1D.max())[0][0]
    array1D = np.delete(array1D,indice_a_deletar, axis=0)

print(arrayTop)    
# [array1D.max(), np.delete(array1D,1,axis=0) for x in range(5)]



array([3, 8, 4, 1, 7, 9, 3, 6, 2, 6])

[9. 8. 7. 6. 6.]


In [152]:
# Exercício 7: Dada uma matriz 2D, encontre os índices dos K maiores valores em cada linha.
matriz2D = np.random.randint(low = 20, high= 31, size =(5,5))
matrizMax = matriz2D.max(axis=1)
display(matriz2D)
matrizMax


array([[23, 21, 24, 27, 29],
       [27, 22, 23, 22, 20],
       [27, 22, 29, 24, 27],
       [28, 25, 22, 24, 27],
       [25, 22, 23, 28, 23]])

array([29, 27, 29, 28, 28])

In [16]:
# Exercício 8: Dado um array numpy 1D, calcule a soma cumulativa dos elementos ao quadrado.
arrayInt = np.random.randint(low = 1, high=11, size = 4)
display(arrayInt)
matrizQuadrados = np.vander(arrayInt, N=5)
display(matrizQuadrados)
matrizQuadrados.sum(axis=1)


array([ 9, 10,  7,  5])

array([[ 6561,   729,    81,     9,     1],
       [10000,  1000,   100,    10,     1],
       [ 2401,   343,    49,     7,     1],
       [  625,   125,    25,     5,     1]])

array([ 7381, 11111,  2801,   781])

In [8]:
# Exercício 9: Dada uma matriz 2D, encontre a média dos elementos nas diagonais principal e secundária.
matrizNum = np.arange(start = 1, stop = 26)
display(matrizNum,np.shape(matrizNum)[0])

matrizNum2D = matrizNum.reshape((5,5))
display(matrizNum2D)

matrizNum2D = np.reshape(matrizNum2D, (5,5))
display(matrizNum2D)

diagPrincipal = np.diag(matrizNum2D).mean()
diagSecundaria = np.diag(np.fliplr(matrizNum2D)).mean()
display("Médias diagonais")
display(diagPrincipal,diagSecundaria)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

25

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

'Médias diagonais'

13.0

13.0

In [32]:
# Exercício 10: Dado um array numpy 1D, encontre o número de valores únicos e sua contagem.
array1D = np.random.randint(low=1, high= 11, size = 15)
display(array1D)
arrayConjunto = np.array(list(set(array1D)))
display(arrayConjunto)
lista = []
for valor in arrayConjunto:
    n = np.count_nonzero( array1D == valor)
    lista.append(n)
print(lista)
matrizresposta = np.array(list((zip(arrayConjunto,np.array(lista)))))
print(matrizresposta) 

array([ 3,  7,  7,  2,  1,  3,  2,  6,  8,  8,  2, 10,  1,  4, 10])

array([ 1,  2,  3,  4,  6,  7,  8, 10])

[2, 3, 2, 1, 1, 2, 2, 2]
[[ 1  2]
 [ 2  3]
 [ 3  2]
 [ 4  1]
 [ 6  1]
 [ 7  2]
 [ 8  2]
 [10  2]]


In [40]:
import pandas as pd

df = pd.DataFrame(matrizresposta,columns= ("Valores","Repetições"))
df["Unico"] = np.where(df["Repetições"] == 1,True,False)
df

Valores  Repetições  Unico
0        1           2  False
1        2           3  False
2        3           2  False
3        4           1   True
4        6           1   True
5        7           2  False
6        8           2  False
7       10           2  False