In [3]:
import numpy as np

In [4]:
""" Arrays 1D 2D 3D"""

a1D = np.array([1,2,3,4])
a2D = np.array([[1,2],[3,4]])
a3D = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(a1D)
print(a2D)

[1 2 3 4]
[[1 2]
 [3 4]]


In [5]:
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
"""Convertendo python em arrays numpy"""
a = np.array([111,112,113], dtype=np.int64)
a

array([111, 112, 113], dtype=int64)

In [ ]:
"""
Existem três tipos de arrays creation

1D arrays
2D arrays
ndarrays
"""

In [24]:
"""1D arrays"""
display(np.arange(start = 1, stop=3, step = 0.2, dtype = float))
np.arange(1,11,1, int)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
"""Valores espaçados igualmente"""
np.linspace(start = 2, stop= 5, num = 6)

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

In [37]:
"""2D arrays"""
"""Matriz identidade"""
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [40]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [42]:
"""Matriz com diagonal escolhida"""
display(np.diag([2,3,4]))

np.diag([2,2,2],1)

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

array([[0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2],
       [0, 0, 0, 0]])

In [48]:
"""matrix de vander, Encontrar os quadrados"""
np.vander(x = [1,2,3,4], N= 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [50]:
"""nArrays"""
"""Matriz de zeros"""
np.zeros((2,3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
"""Matriz de 1"""
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
"""Utilizando metodos do random para criarnarrays"""
np.random.randint(low = 1, high=11, size = (3,3))

array([[5, 5, 3],
       [8, 8, 2],
       [6, 2, 1]])

In [172]:
matriz = np.random.rand(2,3,3).round(3)*1000
matriz.astype(int)

array([[[776, 570, 868],
        [388, 145, 923],
        [620, 305, 964]],

       [[159, 683, 769],
        [745, 439,  91],
        [987, 110, 374]]])

In [182]:
"""modificando arrays existentes"""
lista = [x for x in range(1,11)]
array1D = np.array(lista)
display(array1D)
segundoArray = array1D[:5]
segundoArray += 10
segundoArray



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([11, 12, 13, 14, 15])

In [202]:
A = np.ones((2,2))
B = np.eye(2,2)
C = np.zeros((2,2))
D = np.diag((-3,-4))
display(A,B,C,D)
np.block([[A,B],[C,D]])

array([[1., 1.],
       [1., 1.]])

array([[1., 0.],
       [0., 1.]])

array([[0., 0.],
       [0., 0.]])

array([[-3,  0],
       [ 0, -4]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])