In [4]:
import numpy as np

In [31]:
# Crie um array unidimensional com 5 elementos inteiros aleatórios.

vint = np.array([np.random.randint(5) for x in range(5)])

valoresInt = np.random.randint(5, size = (5))
print(f"vint:{vint}")
print(f"valoresInt:{valoresInt}")

vint:[0 0 0 4 4]
valoresInt:[1 2 1 2 0]
<class 'numpy.ndarray'>


numpy.ndarray

In [33]:
#  2. Crie um array bidimensional de tamanho (3,2) com valores aleatórios de ponto flutuante entre 0 e 1
arrayfloat = np.random.rand(3,2)
arrayfloat23

array([[0.5749624 , 0.34916194],
       [0.01423545, 0.41879419],
       [0.5440853 , 0.39947159]])

In [44]:
#  3. Crie um array tridimensional de tamanho (2,3,4) com valores inteiros aleatórios entre 10 e 20.
array3D = np.random.randint(low = 10, high=21, size = (2,3,4))
array3D

array([[[20, 18, 15, 18],
        [13, 11, 11, 11],
        [11, 11, 12, 12]],

       [[17, 16, 20, 18],
        [19, 18, 19, 16],
        [18, 12, 11, 11]],

       [[11, 16, 11, 10],
        [14, 11, 14, 10],
        [15, 16, 15, 15]]])

In [65]:
# 4. Crie um array unidimensional com 10 elementos iguais a 0.
array1D = np.zeros(10, dtype = int)
array1D

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#  5. Crie um array bidimensional de tamanho (4,4) com valores iguais a 5.
arrayCincos = np.full((4,4),5, dtype= float)
arrayCincos

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [75]:
#  6. Crie um array unidimensional com 10 números pares começando do número 2.

arrayPares = np.arange(start = 2, step= 2, stop=22)
arrayPares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
#  7. Crie um array bidimensional de tamanho (4,4) com valores inteiros aleatórios entre -5 e 5.
array2D = np.random.randint(low = -5, high= 6,size = (4,4))
array2D

array([[-5, -5, -3, -2],
       [-3,  0,  1, -5],
       [ 5, -5, -1, -4],
       [-3, -1, -4, -3]])

In [85]:
#  8. Crie um array unidimensional com 10 elementos com valores decrescentes de 10 a 1.
np.arange(start = 10, stop =0, step=-1)


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [102]:
#  9. Crie um array bidimensional de tamanho (3,3) com valores inteiros aleatórios entre 0 e 9, 
# mas com o elemento central sempre igual a 1.
arrayBd = np.random.randint(10,size = (3,3))
arrayBd[1,1] = 1
arrayBd

array([[0, 2, 2],
       [0, 1, 3],
       [7, 0, 9]])

In [105]:
# 10. Crie um array unidimensional com 20 elementos aleatórios de ponto flutuante entre -1 e 1.
np.random.uniform(size = (20), low = -1, high=1)

array([-0.90170198,  0.78233764,  0.45940516,  0.75855924,  0.80861927,
        0.13845983,  0.84496672, -0.46193362, -0.3676952 ,  0.71561587,
       -0.75076233,  0.45299484, -0.84260076,  0.12875565,  0.99260545,
        0.86530975,  0.70999028, -0.49491591,  0.57588362,  0.61034834])