In [4]:
import numpy as np
import pandas as pd

In [6]:
# Exercício 1:
# Crie um array NumPy 1D com os números de 1 a 10.
np.arange(start = 1, stop = 11, step = 1, dtype= int)




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Exercício 2:
# Crie um array NumPy 2D com uma matriz identidade de ordem 3.
np.identity(3, dtype= int)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Exercício 3:
# Dado o array NumPy abaixo, normalize os valores de cada coluna subtraindo a média e dividindo pelo desvio padrão:

#         matriz =([[1, 5, 9],
#                 [2, 6, 10],
#                 [3, 7, 11],
#                 [4, 8, 12]])

arange_1 = np.arange(start = 1, stop = 13, step= 1)
display(arange_1)

#Alterar dimensão
matriz_1 = arange_1.reshape((3,4))

#Transposta
matriz_1 = matriz_1.transpose()
display(matriz_1)

#media de desvio padrão por coluna
media_1 = np.mean(matriz_1,axis=0)
std_1 = np.std(matriz_1,axis = 0)

#normalização
matriz_1 = (matriz_1 - media_1) / std_1

matriz_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

array([[-1.34164079, -1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079,  1.34164079]])

In [40]:
# Exercício 4:
# Calcule o produto escalar entre dois vetores NumPy:

# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])

a = np.arange(start =1,stop=4)
b = np.arange(start=4,stop=7)

#função calcula propduto escalar
np.dot(a,b)

32

In [43]:
# Exercício 5:
# Dado o array NumPy abaixo, substitua todos os valores maiores que 10 por 10:

# matriz = ([5, 12, 8, 20, 6, 15])

matriz_2 = np.array([5, 12, 8, 20, 6, 15])
display(matriz_2)

matriz_nova = np.where(matriz_2 < 10, matriz_2, 10)
display(matriz_nova)



array([ 5, 12,  8, 20,  6, 15])

array([ 5, 10,  8, 10,  6, 10])

In [48]:
# Exercício 6:
# Dado o array NumPy abaixo, retorne apenas os elementos únicos em ordem crescente:
# matriz = ([3, 5, 1, 3, 2, 2, 5, 7, 6, 7])

matriz_3 = np.array([3, 5, 1, 3, 2, 2, 5, 7, 6, 7])

#maneira 1 
display(np.unique(matriz_3))
#maneira 2 
display(np.array(list(set(matriz_3))))

array([1, 2, 3, 5, 6, 7])

array([1, 2, 3, 5, 6, 7])

In [52]:
# Exercício 7:
# Calcule a média dos elementos de cada coluna de um array NumPy 2D:

#         matriz =([[1, 2, 3],
#                 [4, 5, 6],
#                 [7, 8, 9]])

matriz_4 = np.arange(start=1, stop = 10)
matriz_4 = np.reshape(matriz_4,(3,3))
display(matriz_4)

media_m4 = np.mean(matriz_4,axis=0)
media_m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([4., 5., 6.])

In [56]:
# Exercício 8:
# Dado o array NumPy abaixo, inverta a ordem das colunas:
#         matriz=([[1, 2, 3],
#                 [4, 5, 6],
#                 [7, 8, 9]])
matriz_5 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
display(matriz_5)

matriz_invertida = matriz_5[:,::-1]
matriz_invertida


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [61]:
#exemplo 2 
array = np.arange(1,11)
display(array)

array_invertido = array[::-1]
array_invertido

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [66]:
# Exercício 9:
# Dado o array NumPy abaixo, retorne os índices dos elementos maiores que 5:

# matriz =([1, 6, 2, 8, 3, 4, 9, 7])

matriz_6 = np.array([1, 6, 2, 8, 3, 4, 9, 7])
array_indices = np.where(matriz_6 > 5)

display(array_indices)

(array([1, 3, 6, 7], dtype=int64),)

In [70]:
# Exercício 10:
# Dado o array NumPy abaixo, calcule a soma acumulada de cada linha:

#         matriz =([[1, 2, 3],
#                 [4, 5, 6],
#                 [7, 8, 9]])
matriz_7 = np.arange(1,10)
matriz_7 = np.reshape(matriz_7,(3,3))
np.sum(matriz_7,axis=1)

array([ 6, 15, 24])